### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by HenriDellal** [alaskalinuxuser/app_critical_velocity#1] opened 2017-06-14 14:38 UTC
It crashes on Huawei U3 II (android 5.1). Music plays though. Sadly I can't provide logs.

**Comment by alaskalinuxuser** [comment] 2017-06-14 17:14
Bummer! I wonder what the issue is.... Without any logs, I can't troubleshoot the problem. Thanks for letting me know, though.

**Comment by alaskalinuxuser** [comment] 2017-06-14 17:20
Also, which version are you on? Is it version 1.0 (still on F-Droid) or version 1.2 (on Play Store)?
I have made some updates and improvements. Perhaps if you update to the newer version?

If you use F-Droid, you could also download from my github, under android folder in this repository is the version 1.2 apk to test.

Hope that helps!

**Comment by CrimsonFork** [comment] 2017-06-14 18:14
Same thing on my f-droid 5.1.1/22, just plays a short sound and closes. It almost seems like it's closing itself because there's no OS's error messsage.

**Comment by alaskalinuxuser** [comment] 2017-06-14 18:17
Would you be willing to download the apk from here?
https://github.com/alaskalinuxuser/app_critical_velocity/blob/master/android/criticalvelocity_1_2.apk
and try that? I wonder if it is an F-Droid problem, because the play store downloads have all worked thus far for my friends and family that do not use f-droid.

**Comment by CrimsonFork** [comment] 2017-06-14 21:04
Nope, still doesn't work.

Am 14. Juni 2017 20:17:26 MESZ, schrieb AlaskaLinuxUser <notifications@github.com>:
>Would you be willing to download the apk from here?
>https://github.com/alaskalinuxuser/app_critical_velocity/blob/master/android/criticalvelocity_1_2.apk
>and try that? I wonder if it is an F-Droid problem, because the play
>store downloads have all worked thus far for my friends and family that
>do not use f-droid.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/alaskalinuxuser/app_critical_velocity/issues/1#issuecomment-308515558

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by alaskalinuxuser** [comment] 2017-06-15 03:57
Okay, good to know. Hmm....
What is your screen resolution?

**Comment by CrimsonFork** [comment] 2017-06-15 07:53
480x854

Am 15. Juni 2017 05:57:06 MESZ, schrieb AlaskaLinuxUser <notifications@github.com>:
>Okay, good to know. Hmm....
>What is your screen resolution?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/alaskalinuxuser/app_critical_velocity/issues/1#issuecomment-308621829

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by alaskalinuxuser** [comment] 2017-06-15 15:06
That should work. The game is set to stretch to fill the screen at 480x800. I'm sorry, this is my first time using libGDX in an app. I'm not sure why it doesn't work on your phones. I will look into it.

**Comment by alaskalinuxuser** [comment] 2017-06-15 15:25
Okay, I may have found it. The way that I am loading the textures is taking 150 MB of ram to load on my phone. That may be a bit overkill..... I am going to implement etc1 compression to cut that down to (hopefully) around 50 MB instead.... I will let you know when it is done, and then you can try that.

**Comment by alaskalinuxuser** [comment] 2017-06-15 17:08
Oops, never-mind, I was off by a digit. It is only using about 15 MB of ram. So that's not it.

**Comment by alaskalinuxuser** [comment] 2017-06-15 17:39
Okay, try this:
https://github.com/alaskalinuxuser/app_critical_velocity/blob/master/android/criticalvelocity_1_3.apk
This was based on editing tags to ensure that your phone chooses to run in GL ES 2.0, rather than 1 or 3. That was an issue that others have had in the past. Maybe it will help?

Thanks for helping me troubleshoot this by testing it.

**Comment by HenriDellal** [comment] 2017-06-15 18:30
It doesn't work. I've also tested it on another phone with higher screen resolution (1280x720) and it works. So it's likely a resolution issue.

**Comment by CrimsonFork** [comment] 2017-06-15 21:31
Nope, still exactly the same thing.

Am 15. Juni 2017 20:30:53 MESZ, schrieb HenriDellal <notifications@github.com>:
>It doesn't work. I've also tested it on another phone with higher
>screen resolution (1280x720) and it works. So it's likely a resolution
>issue.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/alaskalinuxuser/app_critical_velocity/issues/1#issuecomment-308829124

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by alaskalinuxuser** [comment] 2017-06-16 13:27
Alright, thanks for bearing with me guys. Could you try this last one?
https://github.com/alaskalinuxuser/app_critical_velocity/blob/master/android/criticalvelocity_1_4.apk

**Comment by CrimsonFork** [comment] 2017-06-16 13:34
Nothing changed. At least on my device.

Am 16. Juni 2017 15:27:10 MESZ, schrieb AlaskaLinuxUser <notifications@github.com>:
>Alright, thanks for bearing with me guys. Could you try this last one?
>https://github.com/alaskalinuxuser/app_critical_velocity/blob/master/android/criticalvelocity_1_4.apk
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/alaskalinuxuser/app_critical_velocity/issues/1#issuecomment-309025957

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by alaskalinuxuser** [comment] 2017-06-16 15:11
Sorry guys, it looks like my game only works on larger screens.

I learned that I as the programmer need to specify in the manifest what screen sizes work. Sorry about the confusion, this is my first game with the libGDX engine. I would have to completely remake the game for smaller screens. I don't have time to do that, so I guess I just have to limit it to larger screens.

In the latest commit, I made the changes to support only larger screens.

https://github.com/alaskalinuxuser/app_critical_velocity/commit/ac20aa0b126b93a9d435a98f9b8ee818b41ff689

**Comment by alaskalinuxuser** [comment] 2017-07-25 21:24
Okay! I found the problem with smaller screens! I ran this through the emulators attempting on screens that were 320x240 and 800x400, all of which crash. After reviewing the logs, I found the problem was actually in the commands for spacing and gaps between the upper and lower walls.

The issue is due to halving the screen overall size number minus the gap. Well, on small screens, the gap is bigger than the screen, so that makes a negative number. You cannot pull a random from a negative number. You can pull a random negative number, but not input a negative number as the random threshold.

So, check out commit: https://github.com/alaskalinuxuser/app_critical_velocity/commit/c89049d4d9fd1204c81fdce63c17f1de98bd3d5f

There are a few screen shots from the emulators, but you should now be able to play on a screen that is only 320x240. However, as the screen gets smaller, the space ship gets "bigger" and the game becomes very difficult on very small screens.

**Comment by alaskalinuxuser** [comment] 2017-07-25 21:25
You can test this out with the 2.7 apk!

**Closed as completed by alaskalinuxuser** 2017-07-25 21:24 UTC
Labels: bug

**Comment by CrimsonFork** [comment] 2017-07-25 21:50
Cool! I'll wait for the Fdroid buikd though.

Am 25. Juli 2017 23:25:27 MESZ, schrieb AlaskaLinuxUser <notifications@github.com>:
>You can test this out with the 2.7 apk!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/alaskalinuxuser/app_critical_velocity/issues/1#issuecomment-317877253

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by alaskalinuxuser** [comment] 2017-07-25 21:52
![medium](https://user-images.githubusercontent.com/19839527/28595452-67d9a614-7140-11e7-815e-cae3ebfdb341.png)
![smallscreen](https://user-images.githubusercontent.com/19839527/28595458-70a59e9c-7140-11e7-8577-6fed63ec152c.png)

As you can see, it is not very practical on very small screens (320x240 or smaller).

**Comment by CrimsonFork** [comment] 2017-07-25 22:17
Is it even technically possible?

Am 25. Juli 2017 23:52:31 MESZ, schrieb AlaskaLinuxUser <notifications@github.com>:
>![medium](https://user-images.githubusercontent.com/19839527/28595452-67d9a614-7140-11e7-815e-cae3ebfdb341.png)
>![smallscreen](https://user-images.githubusercontent.com/19839527/28595458-70a59e9c-7140-11e7-8577-6fed63ec152c.png)
>
>As you can see, it is not very practical on very small screens (320x240
>or smaller).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/alaskalinuxuser/app_critical_velocity/issues/1#issuecomment-317883794

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by alaskalinuxuser** [comment] 2017-07-26 12:56
Well, now the game is set based on screen size, so the thrust, speed, spacing is adjusted as the screen gets smaller. The spacing gets closer, but doesn't move up or down much. I played for a while on the small, medium, and large screens. Small screen seems a bit ridiculous, because you can't see much, so I didn't think it was too fun on that small of a screen. Medium seemed fine, and large was the best.

Also, you should test out 2.8 for me, as fdroid has not advanced passed 1.0 for some reason.
